Cable_paradas/OperacionCable/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('odt/cable/admin/', admin.site.urls),
    path('', include('registro_paradas.urls')),
]

Cable_paradas/registro_paradas/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('home/', views.home, name='home'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),

    # Pestaña detenciones
    path('create/', views.create_event, name='create_record'),
    path('record/update/<pk>', views.update_detenciones, name='update_detencion'),
    path('list_of_stops/', views.list_of_events, name='list_of_stop'),
    path('grafico/', views.grafico_datos, name='grafico_datos'),
    path('reports_stops/', views.generate_report, name='report_stop'),
    path('load_stop_codes/', views.load_stop_codes, name='load_stop_codes'),

    # Pestaña registro de operacion
    path('create_transaction_record/', views.operating_day, name='create_transaction_record'),
    path('list_of_operational/', views.operational_day_list, name='list_of_operational'),
    path('report_operation/', views.generate_report_operation_day, name='report_operation'),
    path('transaction_record/update/<pk>', views.update_operation_day, name='record_update'),

    # Pestaña datos tecnicos
    path('create_technical_data/', views.create_technical_data, name='create_technical_data'),
    path('list_technical_data/', views.technical_data_list, name='list_technical_data'),
    path('report_technical_data', views.generate_report_technical_data, name='report_technical_data'),
]

Cable_paradas/registro_paradas/models.py
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.auth.models import User 
from datetime import datetime, timedelta
from django.db import models

class StopCode(models.Model):
    code = models.CharField(max_length=10)
    description = models.CharField(max_length=70)
    
    def __str__(self):
        return f"{self.code}" + " -- " + f"{self.description}"
    

class Station(models.Model):
    name = models.CharField(max_length=40)
    
    def __str__(self):
        return f"{self.name}"
    

class Cabin(models.Model):
    code = models.CharField(max_length=10)
    
    def __str__(self):
        return f"{self.code}"


class Cabin2(models.Model):
    code = models.CharField(max_length=10)
    
    def __str__(self):
        return f"{self.code}"
    

class Shift(models.Model):
    code_turn = models.CharField(max_length=1)
    
    def __str__(self):
        return f"{self.code_turn}"


class EventType(models.Model):
    name_event = models.CharField(max_length=50)
    
    def __str__(self):
        return f"{self.name_event}"


class StopRegistration(models.Model):
    registration_date = models.DateField()
    stop_code = models.CharField(max_length=255, null=True, blank=True)
    station = models.ForeignKey(Station, on_delete=models.CASCADE)
    start_date = models.TimeField()
    end_date = models.TimeField()
    stop_time = models.IntegerField()
    cabin = models.ForeignKey(Cabin, on_delete=models.CASCADE, null=True, blank=True)
    cabin2 = models.ForeignKey(Cabin2, on_delete=models.CASCADE, null=True, blank=True)
    shift = models.ForeignKey(Shift, on_delete=models.CASCADE)
    observation = models.TextField(null=True)
    inputable = models.CharField(max_length=10, default=True)
    operator = models.ForeignKey(User, on_delete=models.CASCADE)
    event_type = models.ForeignKey(EventType, on_delete=models.CASCADE, null=True)
    
    def save(self, *args, **kwargs):
        # definir si es inputable
        if self.event_type and self.event_type.name_event == "Tormenta electrica":
            self.inputable = False
        
        #Calcular duracion en segundos
        if self.end_date and self.start_date:
            start_datetime =  datetime.combine(datetime.min, self.start_date)
            end_datetime = datetime.combine(datetime.min, self.end_date)
            
            # Si end_date es menor que start_date, asumimos que cruza la medianoche
            if end_datetime < start_datetime:
                end_datetime += timedelta(days=1)
            
            delta = end_datetime - start_datetime
            self.stop_time = int(delta.total_seconds())
        
        else:
            self.stop_time = 0
            
        super().save(*args, **kwargs)
        
        
        # #calcular duracion en segundos
        # if self.end_date and self.start_date:
        #     delta = self.end_date - self.start_date
        #     # self.stop_time = int(delta.total_seconds()/60)
        #     self.stop_time = int(delta.total_seconds())
        # else:
        #     self.stop_time = 0
        # super().save(*args, **kwargs)
    
    def __str__(self):
        return f"{self.registration_date}" + " -- " +f"{self.stop_code}"
    
class Evacuacion(models.Model):
    event_name = models.CharField(max_length=50)
    
    def __str__(self):
        return f"{self.event_name}"
    
    
class Detentions(models.Model):
    detention_name = models.CharField(max_length=50)
    
    def __str__(self):
        return f"{self.detention_name}"
    

class SpeedChange(models.Model):
    speed_name = models.CharField(max_length=50)
    
    def __str__(self):
        return f"{self.speed_name}"
    


class EventStopCode(models.Model):
    event_type = models.ForeignKey(EventType, on_delete=models.CASCADE)

    # Campos para manejar las relaciones genericas
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    related_object = GenericForeignKey('content_type', 'object_id')
    
    class Meta:
        unique_together = ('event_type', 'content_type','object_id')
    
    def __str__(self):
        return f"{self.event_type} - {self.related_object}"
    

class OperationTime(models.Model):
    date = models.DateField()
    start_time = models.TimeField()
    horometer_start = models.DecimalField(max_digits=10, decimal_places=2)
    end_time = models.TimeField(blank=True, null=True)
    horometer_end = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    operator = models.ForeignKey(User, on_delete=models.CASCADE)
    total_time = models.CharField(max_length=10, blank=True, null=True)

    def save(self, *args, **kwargs):
        #Calcular duracion si ambos campos estan completos
        if self.start_time and self.end_time:
            start_datetime =  datetime.combine(datetime.min, self.start_time)
            end_datetime = datetime.combine(datetime.min, self.end_time)
            
            # Si end_date es menor que start_date, asumimos que cruza la medianoche
            if end_datetime < start_datetime:
                end_datetime += timedelta(days=1)
            
            delta = end_datetime - start_datetime
            hours, remainder = divmod(delta.seconds, 3600)
            minutes, seconds = divmod(remainder, 60)

            self.total_time = f"{hours}: {minutes:02d}"
        else:
            self.total_time = None
            
        super().save(*args, **kwargs)


    def __str__(self):
        return f"{self.date}"


class TechnicalData(models.Model):
    date = models.DateField()
    time = models.TimeField()
    temp_motor_variador = models.IntegerField()
    temp_cuarto_variador = models.DecimalField(max_digits=10, decimal_places=2)
    temp_reductor = models.DecimalField(max_digits=10, decimal_places=2)
    temp_reductor_panel = models.IntegerField()
    par = models.IntegerField()
    presion_fs_bar = models.IntegerField()
    presion_fe_bar = models.IntegerField()
    carro_tensor_tunal = models.DecimalField(max_digits=10, decimal_places=2)
    carro_tensor_paraiso = models.DecimalField(max_digits=10, decimal_places=2)
    longitud_de_linea = models.IntegerField()
    viento_p06 = models.IntegerField()
    viento_p16 = models.IntegerField()
    viento_p23 = models.IntegerField()
    operator = models.ForeignKey(User, on_delete=models.CASCADE)


    def __str__(self):
        return f"{self.date}"

Cable_paradas/registro_paradas/forms.py
from django.contrib.auth.models import User
from .models import StopRegistration, OperationTime, TechnicalData
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(max_length=30)
    password = forms.CharField(widget=forms.PasswordInput)


class FormRegister(forms.ModelForm):    
    class Meta:
        model = StopRegistration
        fields = [
            'event_type',
            'registration_date',
            'stop_code',
            'station', 
            'start_date', 
            'end_date', 
            'cabin',
            'cabin2',
            'shift',
            'observation',
        ]
        
        labels = {
            "registration_date": "Fecha de registro",
            "stop_code": "Motivo de parada",
            "station": "Estacion",
            "start_date": "Hora de parada",
            "end_date": "Hora inicio de operacion",
            "cabin": "Cabina 1",
            "cabin2": "Cabina 2",
            "shift": "Turno",
            "event_type": "Tipo de evento",
            "observation": "Observaciones",
        }
        
        widgets = {
            'stop_code': forms.Select(attrs={'class': 'form-control select2'}),
            'registration_date': forms.DateInput(attrs={'type': 'date'}),
            'start_date': forms.TimeInput(attrs={'type': 'time', 'class': 'form-control', 'step': 1}),
            'end_date': forms.TimeInput(attrs={'type': 'time', 'class': 'form-control', 'step': 1})
        }
        
        def clean(self):
            cleaned_data = super().clean()
            event_type = cleaned_data.get("event_type")
            
            if event_type and event_type.name_event == 'Tormenta electrica':
                cleaned_data['inputable'] = 'False'
            else:
                cleaned_data['inputable'] = True
                
            return cleaned_data
        


class FormRegisterUpdate(forms.ModelForm):    
    class Meta:
        model = StopRegistration
        fields = [
            'registration_date',
            'station', 
            'start_date', 
            'end_date', 
        ]
        
        labels = {
            "registration_date": "Fecha de registro",
            "station": "Estacion",
            "start_date": "Hora de parada",
            "end_date": "Hora inicio de operacion",
        }
        
        widgets = {
            'registration_date': forms.DateInput(attrs={'type': 'date'}),
            'start_date': forms.TimeInput(attrs={'type': 'time', 'class': 'form-control', 'step': 1}),
            'end_date': forms.TimeInput(attrs={'type': 'time', 'class': 'form-control', 'step': 1})
        }
        
            
        
class FormOperatingDay(forms.ModelForm):
    class Meta:
        model = OperationTime
        fields = ['date','start_time','horometer_start','end_time','horometer_end']

        labels = {
            "date": "Fecha",
            "start_time": "Hora Inicio", 
            "horometer_start": "Horometro inicio operacion",
            "end_time": "Hora Fin",
            "horometer_end": "Horometro fin operacion"
        }

        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'}),
            'start_time': forms.TimeInput(attrs={'type': 'time', 'class': 'form-control', 'step': 1}),
            'end_time': forms.TimeInput(attrs={'type': 'time', 'class': 'form-control', 'step': 1}),
            'horometer_start': forms.NumberInput(attrs={'type': 'number', 'placeholder': 'Ingrese el horómetro inicial','class': 'form-control'}),
            'horometer_end': forms.NumberInput(attrs={'type': 'number', 'placeholder': 'Ingrese el horómetro final','class': 'form-control'})
        }


class FormTechnicalData(forms.ModelForm):
    class Meta:
        model = TechnicalData
        fields = ["date", "time", "temp_motor_variador", "temp_cuarto_variador", "temp_reductor", "temp_reductor_panel", "par", "presion_fs_bar", "presion_fe_bar", "carro_tensor_tunal",
                  "carro_tensor_paraiso", "longitud_de_linea", "viento_p06", "viento_p16", "viento_p23"]
        labels = {
            "date": "Fecha", 
            "time": "Hora",
            "temp_motor_variador": "Temp motor variador",
            "temp_cuarto_variador": "Temp cuarto variador",
            "temp_reductor": "Temp reductor",
            "temp_reductor_panel": "Temp reductor panel (°C)",
            "par": "Par (%)",
            "presion_fs_bar": "Presion fs bar",
            "presion_fe_bar": "Presion fe bar",
            "carro_tensor_tunal": "Carro tensor tunal",
            "carro_tensor_paraiso": "Carro tensor paraiso",
            "longitud_de_linea": "Longitud de linea (pulsos)",
            "viento_p06": "Viento p06 (m/s)",
            "viento_p16": "Viento p16 (m/s)",
            "viento_p23": "Viento p23 (m/s)",
        }
    

        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'}),
            'time': forms.TimeInput(attrs={'type': 'time', 'class': 'form-control', 'step': 1}),
            'temp_motor_variador': forms.NumberInput(attrs={'type': 'number', 'class': 'form-control'}),
            'temp_cuarto_variador': forms.NumberInput(attrs={'type': 'number', 'class': 'form-control'}),
            'temp_reductor': forms.NumberInput(attrs={'type': 'number', 'class': 'form-control'}),
            'temp_reductor_panel': forms.NumberInput(attrs={'type': 'number', 'class': 'form-control'}),
            'par': forms.NumberInput(attrs={'type': 'number', 'class': 'form-control'}),
            'presion_fs_bar': forms.NumberInput(attrs={'type': 'number', 'class': 'form-control'}),
            'presion_fe_bar': forms.NumberInput(attrs={'type': 'number', 'class': 'form-control'}),
            'carro_tensor_tunal': forms.NumberInput(attrs={'type': 'number', 'class': 'form-control'}),
            'carro_tensor_paraiso': forms.NumberInput(attrs={'type': 'number', 'class': 'form-control'}),
            'longitud_de_linea': forms.NumberInput(attrs={'type': 'number', 'class': 'form-control'}),
            'viento_p06': forms.NumberInput(attrs={'type': 'number', 'class': 'form-control'}),
            'viento_p16': forms.NumberInput(attrs={'type': 'number', 'class': 'form-control'}),
            'viento_p23': forms.NumberInput(attrs={'type': 'number', 'class': 'form-control'}),
        }

Cable_paradas/templates/registro_paradas/create_record.html
{% extends "base.html" %}
{% load static %}

{% block title %}Crear evento de parada{% endblock %}

{% block extra_css %}
  <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
{% endblock %}


{% block content %}

<input type="hidden" id="load-stop-codes-url" value="{% url 'load_stop_codes' %}">

<div class="container mt-5">
    <h1>Crear Registro de Parada</h1>
    {{ form.media }}
    <form method="post" id="stop-registration-form">
      {% csrf_token %}
      <div class="row">
        <div class="col-md-6 mb-3">
          {{ form.event_type.label_tag }}
          {{ form.event_type }}
        </div>
        <div class="col-md-6 mb-3">
          {{ form.registration_date.label_tag }}
          {{ form.registration_date }}
        </div>
        <div class="col-md-6 mb-3">
          {{ form.stop_code.label_tag }}
          {{ form.stop_code }}
        </div>
        <div class="col-md-6 mb-3">
          {{ form.station.label_tag }}
          {{ form.station }}
        </div>
        <div class="col-md-6 mb-3">
          {{ form.start_date.label_tag }}
          {{ form.start_date }}
        </div>
        <div class="col-md-6 mb-3">
          {{ form.end_date.label_tag }}
          {{ form.end_date }}
        </div>
        <div class="col-md-6 mb-3">
          {{ form.cabin.label_tag }}
          {{ form.cabin }}
        </div>
        <div class="col-md-6 mb-3">
          {{ form.cabin2.label_tag }}
          {{ form.cabin2 }}
        </div>
        <div class="col-md-6 mb-3">
          {{ form.shift.label_tag }}
          {{ form.shift }}
        </div>
        <div class="col-md-6 mb-3">
          <label for="id_stop_time">Duración (en segundos)</label>
          <input type="text" id="id_stop_time" name="stop_time" readonly class="form-control" />
        </div>
        <div class="col-md-12 mb-3">
          {{ form.observation.label_tag }}
          {{ form.observation }}
        </div>
        <div class="col-md-12">
          <button type="submit" class="btn btn-success">Guardar Registro</button>
        </div>
      </div>
    </form>
  </div>

{% endblock %}

{% block extra_js %}

  <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
  <script src="{% static 'js/stop_registration.js' %}"></script>

{% endblock %}

Cable_paradas/templates/registro_paradas/create_technical_data.html
{% extends "base.html" %}
{% load static %}

{% block title %}Inicio y fin de la operacion{% endblock %}

{% block extra_css %}
  <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
{% endblock %}


{% block content %}

<div class="container mt-5">
    <h1>Datos tecnicos</h1>
    {{ form.media }}
    <form method="post" id="technical-data-form">
      {% csrf_token %}
      <div class="row">
        <div class="col-md-6 mb-3">
          {{ form.date.label_tag }}
          {{ form.date }}
        </div>
        <div class="col-md-6 mb-3">
          {{ form.time.label_tag }}
          {{ form.time }}
        </div>
        <div class="col-md-3 mb-3">
            {{ form.temp_motor_variador.label_tag }}
            {{ form.temp_motor_variador }}
          </div>
        <div class="col-md-3 mb-3">
          {{ form.temp_cuarto_variador.label_tag }}
          {{ form.temp_cuarto_variador }}
        </div>
        <div class="col-md-3 mb-3">
          {{ form.temp_reductor.label_tag }}
          {{ form.temp_reductor }}
        </div>
        <div class="col-md-3 mb-3">
          {{ form.temp_reductor_panel.label_tag }}
          {{ form.temp_reductor_panel }}
        </div>
        <div class="col-md-3 mb-3">
          {{ form.par.label_tag }}
          {{ form.par }}
        </div>
        <div class="col-md-3 mb-3">
            {{ form.presion_fs_bar.label_tag }}
            {{ form.presion_fs_bar }}
          </div>
        <div class="col-md-3 mb-3">
          {{ form.presion_fe_bar.label_tag }}
          {{ form.presion_fe_bar }}
        </div>
        <div class="col-md-3 mb-3">
          {{ form.carro_tensor_tunal.label_tag }}
          {{ form.carro_tensor_tunal }}
        </div>
        <div class="col-md-3 mb-3">
          {{ form.carro_tensor_paraiso.label_tag }}
          {{ form.carro_tensor_paraiso }}
        </div>
        <div class="col-md-3 mb-3">
          {{ form.longitud_de_linea.label_tag }}
          {{ form.longitud_de_linea }}
        </div>
        <div class="col-md-3 mb-3">
            {{ form.viento_p06.label_tag }}
            {{ form.viento_p06 }}
          </div>
        <div class="col-md-3 mb-3">
          {{ form.viento_p16.label_tag }}
          {{ form.viento_p16 }}
        </div>
        <div class="col-md-3 mb-3">
          {{ form.viento_p23.label_tag }}
          {{ form.viento_p23 }}
        </div>
        <div class="col-md-12">
          <button type="submit" class="btn btn-success">Guardar Registro</button>
        </div>
      </div>
    </form>
  </div>

{% endblock %}

{% block extra_js %}



{% endblock %}

Cable_paradas/templates/registro_paradas/create_transaction_record.html
{% extends "base.html" %}
{% load static %}

{% block title %}Inicio y fin de la operacion{% endblock %}

{% block extra_css %}
  <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
{% endblock %}


{% block content %}

<div class="container mt-5">
    <h1>Registrar inicio y fin de la operacion de cable</h1>
    {{ form.media }}
    <form method="post" id="operation-time-form">
      {% csrf_token %}
      <div class="row">
        <div class="col-md-4 mb-3">
          {{ form.date.label_tag }}
          {{ form.date }}
        </div>
        <div class="col-md-4 mb-3">
          {{ form.start_time.label_tag }}
          {{ form.start_time }}
        </div>
        <div class="col-md-4 mb-3">
            {{ form.end_time.label_tag }}
            {{ form.end_time }}
          </div>
        <div class="col-md-6 mb-3">
          {{ form.horometer_start.label_tag }}
          {{ form.horometer_start }}
        </div>
        <div class="col-md-6 mb-3">
          {{ form.horometer_end.label_tag }}
          {{ form.horometer_end }}
        </div>
        <div class="col-md-12">
          <button type="submit" class="btn btn-success">Guardar Registro</button>
        </div>
      </div>
    </form>
  </div>

{% endblock %}

{% block extra_js %}



{% endblock %}

Cable_paradas/templates/registro_paradas/grafico.html
{% extends "base.html" %}
{% load static %}
{% block title %}Dashboard prueba{% endblock %}
{% block content %} 
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">

<div>
    <h1>Tablero de control de paradas en el sistema de cable</h1>
    <div class="embed-responsive embed-responsive-4by3">
        <iframe class="embed-responsive-item" title="Plantilla_paradas" width="1366" height="768" src="https://app.powerbi.com/view?r=eyJrIjoiN2E1YWU4YmUtNzMzNy00ODg2LWJmYzUtMWY2MGY1ZWMyYzkwIiwidCI6ImFmYWRlNjcyLTUwNjMtNGI5Yi1iYWFmLTg0NWMzZmZkZGIzMCJ9" frameborder="0" allowFullScreen="true"></iframe>
    </div>
</div>



{% endblock %}

Cable_paradas/templates/registro_paradas/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}Pagina principal{% endblock %}

{% block content %}

<div>
  <h3>Operacion Cable - Control de paradas en las cabinas</h3>
</div>

<script src="{% static 'js/test.js' %}"></script>

<div class="container">
  <div class="row">
    <div class="col-md-6 mb-3">
      <div class="alert alert-dark" role="alert">
        <h4><strong>Total de paradas - {{ Paradas|length }}</strong></h4>
        <i> Ultima actualizacion {{ Fecha_hora }}</i>
      </div>
    </div>
    <div class="col-md-6 mb-3">
      <div class="alert alert-dark" role="alert">
        <h4><strong>Total paradas del dia: {{ Paradas_dia|length }}</strong></h4> <i> Ultima actualizacion {{ Fecha_hora }}</i>
      </div>
    </div>
  </div>
</div>


<div class="card">
  <div class="card-header">
    <h5><strong>Estaciones</strong></h5>
  </div>
  <div class="est"></div>
  <div class="container">
    <div class="row">
      <div class="col">
        <div class="card text-bg-danger mb-3" style="width: 18rem;">
          <img src="{% static 'img/tunal.jpg' %}" class="card-img-top img-fluid" alt="Estacion Tunal"
            style="height: 150px; object-fit: cover;">
          <div class="card-body">
            <h5 class="card-title">Tunal</h5>
            <p class="card-text">Total - {{ paradas_station|length }}</p>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="card text-bg-success mb-3" style="width: 18rem;">
          <img src="{% static 'img/JuanPabloII.jpg' %}" class="card-img-top img-fluid" alt="Estacion Juan Pablo II"
            style="height: 150px; object-fit: cover;">
          <div class="card-body">
            <h5 class="card-title">Juan Pablo II</h5>
            <p class="card-text">Total - {{ paradas_station3|length }}</p>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="card text-bg-warning mb-3" style="width: 18rem;">
          <img src="{% static 'img/manitas2.jpeg' %}" class="card-img-top img-fluid" alt="Estacion Manitas"
            style="height: 150px; object-fit: cover;">
          <div class="card-body">
            <h5 class="card-title">Manitas</h5>
            <p class="card-text">Total - {{ paradas_station2|length }}</p>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="card text-bg-secondary mb-3" style="width: 18rem;">
          <img src="{% static 'img/paraiso.jpg' %}" class="card-img-top img-fluid" alt="Estacion Paraiso"
            style="height: 150px; object-fit: cover;">
          <div class="card-body">
            <h5 class="card-title">Paraiso</h5>
            <p class="card-text">Total - {{ paradas_station4|length }}</p>
          </div>
        </div>
      </div>
    </div>
    <div class="est"></div>
  </div>



  <div class="container">
    <div class="card">
      <div class="card-header">
        <h5><strong>Por eventos</strong></h5>
      </div>
      <div class="row">
        <div class="col-md-3 mb-3">
          <div class="alert alert-warning" role="alert">
            <h6 class="card-title">Evacuacion del sistema</h6>
            <p class="card-text">{{ tipo_evento1|length }}</p>
          </div>
        </div>
        <div class="col-md-3 mb-3">
          <div class="alert alert-warning" role="alert">
            <h6 class="card-title">Fallas del sistema</h6>
            <p class="card-text">{{ tipo_evento2|length }}</p>
          </div>
        </div>
        <div class="col-md-3 mb-3">
          <div class="alert alert-warning" role="alert">
            <h6 class="card-title">Detenciones externas</h6>
            <p class="card-text">{{ tipo_evento3|length }}</p>
          </div>
        </div>
        <div class="col-md-3 mb-3">
          <div class="alert alert-warning" role="alert">
            <h6 class="card-title">Cambio de velocidad</h6>
            <p class="card-text">{{ tipo_evento4|length }}</p>
          </div>
        </div>
      </div>
    </div>
  </div>




</div>
{% endblock %}

Cable_paradas/templates/registro_paradas/update_operation_day.html
{% extends "base.html" %}
{% load static %}
{% block title %}Consultar jornadas{% endblock %}
{% block content %}

<div class="container mt-5">
    <h1>Registros de operacion</h1>   
</div>
<div>
    <form method="post">
        <div>
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-success">Actualizar</button>
        </div>
    </form>
</div>


{% endblock %}

Cable_paradas/templates/registro_paradas/update_record.html
{% extends "base.html" %}
{% load static %}
{% block title %}Modificar detencion{% endblock %}


{% block extra_css %}
  <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
{% endblock %}

{% block content %}

<input type="hidden" id="load-stop-codes-url" value="{% url 'load_stop_codes' %}">

<div class="container mt-5">
    <h1>Detalle detencion</h1>   
</div>
<div>
  {{ form.media }}
    <form method="post">
        <div>
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-success">Actualizar</button>
        </div>
    </form>
</div>


{% endblock %}

{% block extra_js %}

  <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
  <script src="{% static 'js/stop_registration.js' %}"></script>

{% endblock %}